### ISSUE TITLE
Unexpected 'throw' on line 141 in GuardTor.php

### ISSUE THREAD

**Issue by anoduck** [mitmelon/guardtor#8]
Running php-7.3 on Apache2 

Experienced an error stating class `GuardTor` not found until I finally forced the requirement by referencing the full path to the script:
```php
require_once __DIR__."/vendor/mitmelon/guardtor/src/GuardTor.php";
```  
Now that it has found the script, I have run into an error:

```php
unexpected 'throw' (T_THROW) in /var/www/vendor/mitmelon/guardtor/src/GuardTor.php on line 141
```  
The line in question is:
```php
$handle = fopen('https://check.torproject.org/exit-addresses', 'rb') or throw new \Exception("Could Not Open the specified Tor exit URl. It might be unavailable");
```

**Comment by mitmelon** [comment]
@anoduck 

To use the library make sure you are using composer and have included the autoload at the begining of your script like this below.

require_once(__DIR__.'/vendor/autoload.php');
//Call guardtor
 $guardtor = new GuardTor();
$guardtor->init();

2) The reason why you get exception on line 141 is because you must have an active internet connection for GuardTor to connect to Tor database.

Make sure you are not offline when using GuardTor on every 24 hours. 

GuardTor fetches content from Tor database every 24 hours and this process requires an active internet connections.

**Comment by anoduck** [comment]
@mitmelon 
1. I do have `require_once(__DIR__.'/vendor/autoload.php');`  
The top of my index.php is as follows:  
```php  
/**                                                                                                                                                            
 *  For guardtor (experimental) DDOS protector                                                                                                                 
 */                                                                                                                                                            
                                                                                                                                                               
require_once __DIR__."/vendor/autoload.php";                                                                                                                 
require_once __DIR__.'/vendor/mitmelon/guardtor/src/GuardTor.php';                                                                                           
// Start guardtor session                                                                                                                                      
$guardTor = new GuardTor();                                                                                                                                  
                                                                                                                                                               
// Configuration options                                                                                                                                       
$guardTor->blocktor = false;
$guardTor->block_request = false;

// Call init last after options
$guardTor->init();
```  
If I do not add `require_once __DIR__.'/vendor/mitmelon/guardtor/src/GuardTor.php'; `  
I receive the following error message:   
```php
PHP Fatal error:  Uncaught Error: Class 'GuardTor' not found in /var/www/index.php:27\nStack trace:\n#0 {main}\n  thrown in /var/www/index.php on line 27
```  
So for some reason GuardTor is not being loaded along with autoload.php, regardless of being required in the composer.json file and installed.  Why it is not picking up and requiring GuardTor, I do not know. So, to work around this error, I just directly require GuardTor by path.  

My output from `composer diagnose` is:  
```sh
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.1.0
PHP version: 7.1.3 - Package overridden via config.platform, actual: 7.3.27
PHP binary path: /usr/local/bin/php-7.3
OpenSSL version: LibreSSL 3.2.2
cURL version: 7.72.0 libz 1.2.3 ssl LibreSSL/3.2.2
zip: extension present, unzip present
```  
----

2. My most humble and sincere apologies. I left out that the "throw error" was a **parse error**. Full output this time:  
```php
PHP Parse error:  syntax error, unexpected 'throw' (T_THROW) in /var/www/vendor/mitmelon/guardtor/src/GuardTor.php on line 141
```  
I most definitely have network connection, it is a live server.

**Comment by mitmelon** [comment]
@anoduck 

Ok... This must be a bug for PHP 7.3.  Replace the throw new exception on line 141 with 

`or call_user_func(function() { throw new \Exception("Could Not Open the specified Tor exit URl. It might be unavailable");});`

Try this if it works.

By morning I will correct the bug and merge the pull request for version 1.0.0 and the main version...

**Comment by anoduck** [comment]
@mitmelon 
It seems to accept the first suggestion, but :( it then moves to the next occurrence of 'throw' on line 171. So it appears the syntax of all occurrences of 'throw' will need to be modified. I am not sure if this is specifically a 7.3 issue or if it also occurs in 7.4. If the error does not occur in 7.4, I could just upgrade my installation of php.

**Comment by mitmelon** [comment]
@anoduck 

Thank you for getting back...

All the occurences will be corrected and updated.

You can maintain the 7.3 version... The problem is with guardTor for 7.3

On PHP 8 this errors are silent...

**Comment by mitmelon** [comment]
@anoduck 

For now yes It should if you configured it well... But not 100% strong enough... But will be able to block some malicious requests.

But am working on another release which will be out soon that will be able to detect spammed request, detect DNS poisoning, filter request head injections, block all dangerous bots, check codes for vunerabilities, block All SQL injections, temporally lock website if under attack and raise an alarm to the owners and filter bad comments in forms.

This features will be present in the next release on version 2.0.0. All versions of 1 will just be bugs corrections without any features added.

You can support me by donating for this project using https://www.buymeacoffee.com/mitm to make the release fast.

Please note that you will need redis server on your website for GuardTor to limit brute force attacks...
